"""empty message

Revision ID: 18767951336f
Revises: d5420835fc93
Create Date: 2023-11-27 19:45:18.865652

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '18767951336f'
down_revision = 'd5420835fc93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discount_rules')
    with op.batch_alter_table('billing_record', schema=None) as batch_op:
        batch_op.drop_column('discounted_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discounted_amount', mysql.FLOAT(), nullable=False))

    op.create_table('discount_rules',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('spending_amount', mysql.FLOAT(), nullable=False),
    sa.Column('discount_percentage', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
