"""empty message

Revision ID: 815218f9a99c
Revises: eff5be6cf91c
Create Date: 2023-11-24 21:29:18.087170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815218f9a99c'
down_revision = 'eff5be6cf91c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discount_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spending_amount', sa.Float(), nullable=False),
    sa.Column('discount_percentage', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emp_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emp_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    op.drop_table('discount_rules')
    # ### end Alembic commands ###
