"""empty message

Revision ID: b5177edf7ac5
Revises: 18767951336f
Create Date: 2023-12-26 21:05:01.737862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5177edf7ac5'
down_revision = '18767951336f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index('emp_id')
        batch_op.drop_column('emp_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emp_id', mysql.VARCHAR(length=10), nullable=False))
        batch_op.create_index('emp_id', ['emp_id'], unique=False)

    # ### end Alembic commands ###
