"""empty message

Revision ID: d5420835fc93
Revises: 5e3fed0a2820
Create Date: 2023-11-26 22:50:33.548843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5420835fc93'
down_revision = '5e3fed0a2820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_record', schema=None) as batch_op:
        batch_op.drop_constraint('billing_record_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'order', ['order_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('menu_order', schema=None) as batch_op:
        batch_op.drop_constraint('menu_order_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('menu_order_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'order', ['order_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'dishes', ['dish_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('order_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_model', ['customer_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_ibfk_1', 'user_model', ['customer_id'], ['id'])

    with op.batch_alter_table('menu_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('menu_order_ibfk_1', 'dishes', ['dish_id'], ['id'])
        batch_op.create_foreign_key('menu_order_ibfk_2', 'order', ['order_id'], ['id'])

    with op.batch_alter_table('billing_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('billing_record_ibfk_1', 'order', ['order_id'], ['id'])

    # ### end Alembic commands ###
