"""empty message

Revision ID: eff5be6cf91c
Revises: a9ed51ef73c5
Create Date: 2023-11-24 20:35:29.857008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eff5be6cf91c'
down_revision = 'a9ed51ef73c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.drop_column('D_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('D_price', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('price')

    # ### end Alembic commands ###
